# Generated by Django 3.2 on 2022-09-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20220915_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
