# Generated by Django 3.2 on 2022-09-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_rename_job_id_jobcandidatemapping_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='grammar_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionlevelrating',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.interviewer'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='past_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='past_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_exp',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobcandidatemapping',
            unique_together={('job_id', 'candidate')},
        ),
    ]
