# Generated by Django 3.2 on 2022-09-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20220915_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='past_role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcandidatemapping',
            name='similarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.level')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.job')),
            ],
            options={
                'unique_together': {('role', 'level')},
            },
        ),
    ]
