# Generated by Django 3.2 on 2022-09-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20220915_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.transcript'),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='email',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionlevelrating',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.interview'),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('candidate', 'job', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlevelrating',
            unique_together={('question', 'interview')},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='result',
        ),
        migrations.RemoveField(
            model_name='questionlevelrating',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='questionlevelrating',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='questionlevelrating',
            name='level',
        ),
    ]
